/***********************************************************************/
/*                                                                     */
/*  FILE        :typedefine.h                                          */
/*  DATE        :Tue, Feb 02, 2010                                     */
/*  DESCRIPTION :define scalar types.                                  */
/*  CPU GROUP   :2K                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.12).    */
/*                                                                     */
/***********************************************************************/

/*************************************************
 *  COMPILER for R8C/Tiny
 *
 *  Copyright(c) 2004 Renesas Technology Corp.
 *  And Renesas Solutions Corp.,All Rights Reserved.
 *
 *  typedef for startup
 *
 * $Date: 2005/11/01 04:31:54 $
 * $Revision: 1.4 $
 ************************************************/
#ifndef __TYPEDEF__
	typedef signed char 	_SBYTE;
	typedef unsigned char 	_UBYTE;
	typedef signed short    _SWORD;
	typedef unsigned short 	_UWORD;
	typedef signed int 		_SINT;
	typedef unsigned int 	_UINT;
	typedef signed long 	_SDWORD;
	typedef unsigned long 	_UDWORD;
	typedef signed long long 	_SQDWORD;
	typedef unsigned long long 	_UQDWORD;
#endif

#define __TYPEDEF__
